#include "StdAfx.h"
#define BOOST_TEST_MODULE LexerTests
#include "StringLiteralTests.h"
#include "KeywordTests.h"
#include "OperatorTests.h"
#include "AtomTests.h"
#include "SeparatorTests.h"
#include "CommentTests.h"
#include "VariableTests.h"
#include "CharacterLiteralTests.h"
#include "ExplicitRadixLiteralTests.h"
#include "DecimalLiteralTests.h"
#include "FloatLiteralTests.h"
#include "RealErlangFileTests.h"