#pragma once
#include <string>
#include <vector>
#include <utility>
#include <functional>
#include <algorithm>
#include <iterator>
#include <iostream>
#include <ErlangTokens.h>
#include "ErlangLexer.h"
#include "ErlangParser.h"
#include "TestUtil.h"
#include <boost/spirit/include/lex_lexertl.hpp>
#include "CommentSkipper.h"
